#!/bin/sh

# check command exists
if ! type octo > /dev/null; then
  echo 'octo not installed, you need to "npm install -g octopus-cli" to proceed.'
  exit 1;
fi

echo 'Syncing module versions (octo modules sync --save):'
octo modules sync --save

echo 'Syncing module deps (octo deps sync --save):'
octo deps sync --save

if [[ -n $(git status --porcelain) ]]; 
	then 
	echo "octo deps/modules found things to update - review them, push and commit.";
	exit 1;
fi
